### ISSUE TITLE
The impact of sampling method on serialization effect

### ISSUE THREAD

**Issue by Rfdfz** [Pointcept/PointTransformerV3#10]
Hi, if we use FPS instead of Grid Sample for the point cloud in the data preprocessing stage, what impact will it have on the serialization effect?
I followed the annotations below in the code. It works, but I'm not sure if the point cloud is being serialized correctly.
```# if you don't want to operate GridSampling in data augmentation,
# please add the following augmentation into your pipline:
# dict(type="Copy", keys_dict={"grid_size": 0.01}),
# (adjust `grid_size` to what your want)
```

**Comment by Gofinge** [comment]
Good question! In my opinion, it works with FPS, yet tuning a good initial grid size (no need for grid sampling, just copy it into data dict) is still necessary. In that case, multiple points will exist in one single grid, but it won't affect serialization (and SpConv also supports such a pattern, MinkEngine does not support it).

**Comment by Rfdfz** [comment]
Thanks for your answer!!!
