### ISSUE TITLE
How to visualize the segmentation result of ScanNet? Any Suggestion?

### ISSUE THREAD

**Issue by garrisonz** [Pointcept/PointTransformerV3#106]
Thanks for your great work!

I have run test.sh to get the segmentation result under `result/submit` folder.
I would like to visualize the segmentation result of ScanNet scene. Any suggestion? thanks!

**Comment by Gofinge** [comment]
1. Map segment index to color with scannet official colormap.
2. Export to mesh with open3d (check Pointcept.utils.visualizaton.save_point_cloud)
3. Visualization with Meshlab.

**Comment by garrisonz** [comment]
Thanks a lot!
