### ISSUE TITLE
When will "instance segmentation" be to release?

### ISSUE THREAD

**Issue by garrisonz** [Pointcept/PointTransformerV3#108]
Thanks for your great work again!

I am interesting in the todo "Release config and record of indoor instance segmentation;".
May I know when the pre-train model of indoor instance segmentation will be release? thanks

**Comment by bututoubaobei-0108** [comment]
There are some pretrained models in the hugging face: https://huggingface.co/Pointcept/PointTransformerV3/tree/main/s3dis-semseg-pt-v3m1-0-rpe/model

**Comment by garrisonz** [comment]
okay, thanks.
