### ISSUE TITLE
validation and test

### ISSUE THREAD

**Issue by Charlie839242** [Pointcept/PointTransformerV3#13]
Hi, thanks for sharing your great work!

I found that the best mIOU of S3DIS is different for validation and set, but boh sets are Area 5. 
Then I found that the test set did the data augmentation while the validation didn't. 

I wonder why not unify them. Is this ok?

**Comment by Gofinge** [comment]
Hi, check readme here (https://github.com/Pointcept/Pointcept?tab=readme-ov-file#testing), we adopt a more precise yet time-consuming testing strategy, so we do not use it during validation.
