### ISSUE TITLE
 Inquiry About Object Detection Configuration and Code Release

### ISSUE THREAD

**Issue by JUNJIE99** [Pointcept/PointTransformerV3#22]
Hi~
Thank you for your work. 

Are there any plans to release the object detection configuration and code?

**Comment by Gofinge** [comment]
I haven’t cleaned the code and I am currently fully devoted to a new research program. I will have some time in a few months later. If you need the raw code, you can email me for a request.

**Comment by JUNJIE99** [comment]
> I haven’t cleaned the code and I am currently fully devoted to a new research program. I will have some time in a few months later. If you need the raw code, you can email me for a request.
Thank you!
