### ISSUE TITLE
Release plan of PTv3 code

### ISSUE THREAD

**Issue by 99DHL** [Pointcept/PointTransformerV3#3]
Thank you for your great work! Could you provide a rough estimate of when the code for PTv3 and the configuration and weights for ScanNet/S3DIS will be released?

**Comment by Gofinge** [comment]
What about tomorrow? The scratch ScanNet and S3DIS weight for the released version is ready, and then I will work on other dataset scratch weights. After that, I will train the best model version with multi-dataset joint training. I will try my best to release all the weight for the released version model before Feb 2024.

**Comment by 99DHL** [comment]
Thank you for your kind response!
