### ISSUE TITLE
about block lr scaler

### ISSUE THREAD

**Issue by thuliu-yt16** [Pointcept/PointTransformerV3#30]
In the paper, you mentioned that you set the block lr scaler as 0.1. Does it mean for all the parameters in `Block` have a 1/10 learning rate, e.g. 5e-4 for indoor semantic segmentation?

**Comment by Gofinge** [comment]
Here: https://github.com/Pointcept/Pointcept/blob/main/configs/scannet/semseg-pt-v3m1-0-base.py#L65
