### ISSUE TITLE
SemanticKITTI config

### ISSUE THREAD

**Issue by FT-Zheng** [Pointcept/PointTransformerV3#38]
Thank you for your work! I tried to reproduce the config used by ptv3 on SemanticKITTI based on the ptv3-nuScenes and other SemanticKITTI configs, but the mIoU on SemanticKITTI val only reached 67.0. May I ask the channels and patch_size you set up on SemanticKITTI? I'm not sure what's wrong with the config I reproduce.

**Comment by FT-Zheng** [comment]
Thank you for your reply. I will try again.

**Comment by xiaosa269** [comment]
Hello, have you encountered the error "**assert depth * 3 + len(self.offset).bit_length() <= 63**" while training ptv3-nuScenes and SemanticKITTI with ptv3? How did you resolve it? Thank you very much for your response.

**Comment by kabouzeid** [comment]
I would also be interested in the semantic kitti config file

**Comment by Gofinge** [comment]
Sorry for the long wait. I will include them in the next version of the codebase, about 1-2 months after the cvpr deadline.

**Comment by mattpoggi** [comment]
Hi @Gofinge , any news about this? :)
