### ISSUE TITLE
Can you provide a default config for 24G GPU device?

### ISSUE THREAD

**Issue by garrisonz** [Pointcept/PointTransformerV3#40]
Thansk for your great work!

I have follow the README to install PTv3, and run the following command on GPU 3090, 24G
```
sh scripts/train.sh -p python -d scannet -c semseg-pt-v2m2-0-base -n semseg-pt-v2m2-0-base
```

torch.cuda.OutOfMemoryError error appears.
Can you provide a default config requiring less gpu memory? Thanks
Less GPU requirement quickstart example is more friendly to new birds. Thansk again

**Comment by garrisonz** [comment]
It work fine when I set batch_size to 2

**Comment by QWTforGithub** [comment]
> It work fine when I set batch_size to 2

Can you tell me what mIoU you can achieve on ScanNet? I only have 74+mIoU here.
