### ISSUE TITLE
Question about Test mode of GridSample

### ISSUE THREAD

**Issue by pycoco** [Pointcept/PointTransformerV3#47]
thanks for your great work. I'm confuse about why to use a for loop with the max points of the all voxels here. could you please tell me the reason? And the input data is a list which is different with train( a dict).
https://github.com/Pointcept/Pointcept/blob/c759914eb3ab8255455c80c00472ab0bc664a20c/pointcept/datasets/transform.py#L855

**Comment by Gofinge** [comment]
Make sure each point belongs to a sub point cloud and is directly predicted by network.
