### ISSUE TITLE
Sample input for Point object.

### ISSUE THREAD

**Issue by JamesMcCullochDickens** [Pointcept/PointTransformerV3#58]
Hello thank you for your work, I am learning a lot reading this paper. 

I want to train this model on a custom point cloud task, and I am wondering if there is sample code related to creating a mock Point dict object, for instance suppose I have a batch of 8 point clouds with 1024 points each. Would this be an appropriate input dict? 

{ "coords" = torch.rand((8, 1024, 3)), 
"grid_size" = 0.02,
"batch": 8,
"feat": torch.rand((8, 1024, 1))
}
?

**Comment by mxmm2123** [comment]
Hi @JamesMcCullochDickens, i see you closed issue as complete, have you solved the problem yet?
I was try to run this model, but I don't clear about model input. If you was solved it, can you give me sample input for model?

**Comment by JamesMcCullochDickens** [comment]
Yes, something like:
```
num_feat = 3
model = PointTransformerV3(cls_mode=True, in_channels=num_feat, enc_patch_size=(512, 512, 512, 512, 512)).cuda()
patch_size = 1024
batch_size = 6
batch_vals = torch.arange(0, batch_size, step=1)
repeat_vals = torch.tensor([patch_size for i in range(batch_size)])
batch_vals = torch.repeat_interleave(batch_vals, repeat_vals).cuda()
sample_data = {"feat": torch.rand((patch_size*batch_size, num_feat)).cuda(), "batch": batch_vals,
               "coord": torch.rand((patch_size*batch_size, 3)).cuda(), "grid_size": 0.01}
sample_dict = Point(sample_data)
output = model(sample_dict)
```

**Comment by mxmm2123** [comment]
@JamesMcCullochDickens thank you, can you explain about input and output:
```
output.keys()
dict_keys(['feat', 'coord', 'grid_coord', 'serialized_code', 'serialized_order', 'serialized_inverse', 'serialized_depth', 'batch', 'pooling_inverse', 'pooling_parent', 'offset', 'sparse_shape', 'sparse_conv_feat', 'pad', 'unpad', 'cu_seqlens_key'])
```
what is this? I don't clear about input and output of model.

**Comment by JamesMcCullochDickens** [comment]
For the features you want point.feat, where depending on your data's spatial distribution the amount pooled may differ. 

For classification I have a function:

    def forward(self, point):
        feat = point.feat
        offsets = point.offset
        num_points = offsets.shape[0]
        d = feat.shape[-1]
        avg_feats = torch.zeros((num_points, d), dtype=feat.dtype, device=feat.device)
        for point_num in range(num_points):
            if point_num == 0:
                lb = 0
                ub = offsets[point_num]+1
            else:
                lb = ub-1
                ub = offsets[point_num]+1
            range_ = ub-lb
            if range_ < 1:
                avg_feats[point_num] = torch.zeros(1).to(device=feat.device)
            avg_feats[point_num] = torch.mean(feat[lb:ub])
        return avg_feats

**Comment by mxmm2123** [comment]
@JamesMcCullochDickens, my project is segmentation  on custom data, then now i test on preprocessing scannet data download from repo with set cls_model=False, so it will don't need get embeding to manual feed to mlp head, right? then what i revice? i don't see any key like 'predict_labels' in output. you can check my kaggle notebook [here](https://www.kaggle.com/code/manh152924/notebookfde24e2eff)(need restart notbook after complie pointops)

**Comment by JamesMcCullochDickens** [comment]
You need to add a semantic segmentation head, the provided model is just a backbone. Should be relatively easy, you could use 1D convolutional to go from the encoding channels to class channels, then just standard segmentation  losses (cross entropy). During inference you need to do argmax. I think maybe a bit more reading on this topic will help, you might need to tweak a lot and it won't be easy to describe in a github issue.

**Comment by Gofinge** [comment]
> You need to add a semantic segmentation head, the provided model is just a backbone. Should be relatively easy, you could use 1D convolutional to go from the encoding channels to class channels, then just standard segmentation losses (cross entropy). During inference you need to do argmax. I think maybe a bit more reading on this topic will help, you might need to tweak a lot and it won't be easy to describe in a github issue.

Thx!

**Comment by mxmm2123** [comment]
> Bạn cần thêm một đầu phân đoạn ngữ nghĩa, mô hình được cung cấp chỉ là xương sống. Sẽ tương đối dễ dàng, bạn có thể sử dụng tích chập 1D để chuyển từ kênh mã hóa sang kênh lớp, sau đó chỉ cần mất phân đoạn chuẩn (entropy chéo). Trong quá trình suy luận, bạn cần thực hiện argmax. Tôi nghĩ có lẽ đọc thêm một chút về chủ đề này sẽ giúp ích, bạn có thể cần phải điều chỉnh rất nhiều và sẽ không dễ để mô tả trong một vấn đề trên github.

@JamesMcCullochDickens thank you, I have reasearch on processing dataset file of Pointcept and got some really useful information.
