### ISSUE TITLE
"Trainer: 'DefaultSegmentorV2 is not in the models registry'"

### ISSUE THREAD

**Issue by hpc100** [Pointcept/PointTransformerV3#61]
Hello,
Thank's for your amazing works.

Actually, I try to install PTV3 and I have this error : 
 `KeyError: "Trainer: 'DefaultSegmentorV2 is not in the models registry'"`
I didn't find any infos on this error. Any ideas ?

Thank's in advance

**Comment by hpc100** [comment]
Check all pointcept/pointtrasnformer files is correctly import

**Comment by BlackNightdd** [comment]
Hello.
I also encountered the same problem, but I don't know which files were not imported correctly.
I searched "DefaultSegmentorV2", but I didn't find this class, so I don't know how to solve this problem.
Do you have any suggestions? Thank you very much!

**Comment by Gofinge** [comment]
Hey, the default segmentor v2 should located here: "https://github.com/Pointcept/Pointcept/blob/main/pointcept/models/default.py#L36"

**Comment by BlackNightdd** [comment]
> Hey, the default segmentor v2 should located here: "https://github.com/Pointcept/Pointcept/blob/main/pointcept/models/default.py#L36"

Thank you. I found it. I found that this file is different from the file I have downloaded. Now I replace it. Thank you very much!
