### ISSUE TITLE
请教下，点的序列化是怎么操作的

### ISSUE THREAD

**Issue by haduoken** [Pointcept/PointTransformerV3#64]
看了论文没看懂，代码里面又是各种位操作（也没看懂 orz）

如果方便的话，希望能够形象些讲解下

**Comment by haduoken** [comment]
@yxlao @Gofinge

**Comment by haduoken** [comment]
https://www.bilibili.com/video/BV1Sf4y147J9/?spm_id_from=333.337.search-card.all.click&vd_source=a36323d3893f862d9c1bc8ac1a8c9a42
看懂了，主要是要设计填充曲线保证局部结构

**Comment by Gofinge** [comment]
这个动画好牛逼啊，我要是会做这个，也就不会那么抽象了
