### ISSUE TITLE
How/Where to set ['offset'] or ['batch'] for the input dict with a custom dataset?

### ISSUE THREAD

**Issue by Urwik** [Pointcept/PointTransformerV3#69]
Hello! I'm trying to use the PTV3 model with a custom dataset, but I've been looking at current repository and Pointcept repository but I couldn't find where or how should set the 'offset' or the 'batch' value. I can set it manually but I don't know where should be the right place. 

Thanks in advance!

**Comment by Urwik** [comment]
Hi there,

I've already figured it out using the "Collect" transform you provided in the Pointcept repository ("Pointcept/pointcept/datasets/transforms.py"). Thanks so much for your help!

**Comment by Gofinge** [comment]
Sorry for the late response. I've been really busy recently.
