### ISSUE TITLE
Question About Training Consistency and Random Seed Effects

### ISSUE THREAD

**Issue by xiaosa269** [Pointcept/PointTransformerV3#74]
Hello, thank you very much for your work. I noticed that if I train twice using the same configuration, I get different training results. Is this due to the setting of the random seed?

If I want to fix the random seed, is it sufficient to set “seed = a number” in the config? Will this ensure that the results of the two training sessions are the same?

If using an unfixed random seed, how do you determine whether the improvement in results is due to the new module added to the network or just the difference in random seed?

Thank you very much for your explanation.

**Comment by Gofinge** [comment]
Hi, I think it is very hard to fix training results with the same random seed for many 3D operators like SpConv. It is common that two runs get different results. I suggest that don't care too much about that.

**Comment by xiaosa269** [comment]
> Hi, I think it is very hard to fix training results with the same random seed for many 3D operators like SpConv. It is common that two runs get different results. I suggest that don't care too much about that.

Thank you for your response. Now, I train 2-3 times and take the average to evaluate the performance.

**Comment by adithyamurali** [comment]
Hi @xiaosa269 thank you for the question. Do you remember how big your differences were when you set different random seeds?

**Comment by Gofinge** [comment]
Hi, I think it's pretty common to observe a 1-2% variation with different random seeds when training a 3D backbone from scratch. This is mostly due to the small scale of 3D data. However, using techniques like PPT (multi-dataset joint training) can make the results more stable, although they are still not entirely consistent.

We are currently working on a self-supervised PTv3 model, which is powerful and achieves strong results even with linear probing. These results are very stable and perform well on datasets with an extremely small data scale. Please look forward to the next update of Pointcept, expected around the end of this year.

**Comment by Gofinge** [comment]
> > Hi, I think it is very hard to fix training results with the same random seed for many 3D operators like SpConv. It is common that two runs get different results. I suggest that don't care too much about that.
> 
> Thank you for your response. Now, I train 2-3 times and take the average to evaluate the performance.

I usually run 2-3 times and take the maximum as the final result

**Comment by xiaosa269** [comment]
> Hi @xiaosa269 thank you for the question. Do you remember how big your differences were when you set different random seeds?

Hello, I trained on my own small dataset, and the differences are not significant. The largest mIoU difference does not exceed 1%。

**Comment by xiaosa269** [comment]
> > > Hi, I think it is very hard to fix training results with the same random seed for many 3D operators like SpConv. It is common that two runs get different results. I suggest that don't care too much about that.
> > 
> > 
> > Thank you for your response. Now, I train 2-3 times and take the average to evaluate the performance.
> 
> I usually run 2-3 times and take the maximum as the final result

I’m also using this strategy now, looking forward to the next update of Pointcept.

**Comment by Gofinge** [comment]
> > Hi @xiaosa269 thank you for the question. Do you remember how big your differences were when you set different random seeds?
> 
> Hello, I trained on my own small dataset, and the differences are not significant. The largest mIoU difference does not exceed 1%。

Good to hear that.

**Comment by Gofinge** [comment]
> > > > Hi, I think it is very hard to fix training results with the same random seed for many 3D operators like SpConv. It is common that two runs get different results. I suggest that don't care too much about that.
> > > 
> > > 
> > > Thank you for your response. Now, I train 2-3 times and take the average to evaluate the performance.
> > 
> > 
> > I usually run 2-3 times and take the maximum as the final result
> 
> I’m also using this strategy now, looking forward to the next update of Pointcept.

Working on this now. We will soon release a super powerful self-supervised model, and the weight should be available in January of next year after some reviewing process.
