### ISSUE TITLE
About shuffle_orders

### ISSUE THREAD

**Issue by LMMMEng** [Pointcept/PointTransformerV3#76]
I've observed that shuffle_orders are enabled during both training and testing. However, during testing, ```torch.randperm``` generates different results each time inference is performed, which could lead to inconsistent inference results for the same sample across different runs. Could you please clarify this? Thanks a lot!

**Comment by Gofinge** [comment]
Hi, it doesn't matter as it won't be a huge difference. The model already learns to fit the different patterns of serialization. You can fix the order during the inference phase if you care about consistency.

**Comment by LMMMEng** [comment]
Thanks a lot.
