### ISSUE TITLE
What is the segmentation head of the model?

### ISSUE THREAD

**Issue by czy20000902** [Pointcept/PointTransformerV3#85]
Hello, I'm trying to use the model to segment my custom data. But there doesn't seem to be a segmentation head. Do you use the same seg_head as PTv2 or something else?

**Comment by Gofinge** [comment]
Sorry, I didn't get the question. Our default config is for semantic segmentation.

**Comment by czy20000902** [comment]
Sorry for the confusion. I mean when I set "cls_mode=False", the output is a Point whose feat is of shape (N, C) where C is 64 instead of num_classes like PTv1 and PTv2. I was wondering how to generate the semantic mask from this feature tensor

**Comment by Gofinge** [comment]
Hi, I move it here (https://github.com/Pointcept/Pointcept/blob/main/pointcept/models/default.py#L45)
