### ISSUE TITLE
Pointcloud ordering

### ISSUE THREAD

**Issue by Aryan-Satpathy** [Pointcept/PointTransformerV3#88]
Dear authors,

Thank you for your tremendous work. I want to use PointTransformerV3 as an encoder for a downstream task that requires embedding dimension (N, D), where N is the number of points in the input pointcloud. The input order is very important for the model used for the downstream task. 

I wondered if using PointTransformerV3 with cls_mode = False (to get embedding dim = (N, D)) changes the order of the output features.

**Comment by Gofinge** [comment]
Hi, it won't change the order of the input source. Feel free to use it.

**Comment by Aryan-Satpathy** [comment]
Thank you for your response.
