### ISSUE TITLE
Is the operation of obtaining the final results similar to Test-Time Augmentation?

### ISSUE THREAD

**Issue by Sylva-Lin** [Pointcept/PointTransformerV3#94]
The test code iterates multiple times through partial results, accumulating them to obtain the final prediction. Is this approach similar to the Test-Time Augmentation used in other methods?
![image](https://github.com/user-attachments/assets/54054c34-2a82-44d2-8337-9ec0b4038652)

**Comment by Gofinge** [comment]
Yeah, it is a kind of TTA. I more detailed explanation is here: https://github.com/Pointcept/Pointcept?tab=readme-ov-file#testing
